# Generated by Django 4.1.7 on 2023-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
