# Generated by Django 4.1.7 on 2023-04-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sub_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_cat',
            name='img',
            field=models.ImageField(upload_to='product'),
        ),
    ]
