# Generated by Django 4.1.7 on 2023-04-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('datetime', models.CharField(max_length=20)),
            ],
        ),
    ]
