# Generated by Django 4.1.7 on 2023-04-10 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_catt'),
    ]

    operations = [
        migrations.CreateModel(
            name='head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='catt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.head'),
        ),
    ]
