# Generated by Django 4.1.7 on 2023-04-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_head_alter_category_catt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catt',
        ),
    ]
