# Generated by Django 4.1.7 on 2023-04-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_category_catt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catt',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
