# Generated by Django 4.1.7 on 2023-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_main_category_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_cat',
            name='d1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_cat',
            name='d2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_cat',
            name='d3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_cat',
            name='d4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
