# Generated by Django 4.1.7 on 2023-04-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_sub_cat_d1_sub_cat_d2_sub_cat_d3_sub_cat_d4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_model',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='otp_model',
            name='otp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sub_cat',
            name='price',
            field=models.IntegerField(),
        ),
    ]
