# Generated by Django 4.1.7 on 2023-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_otp_model_number_alter_otp_model_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_model',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
