# Generated by Django 4.1.7 on 2023-04-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ip',
        ),
    ]
