# Generated by Django 4.1.7 on 2023-04-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order_orderitem_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
